'use client';

import { useState, useEffect } from 'react';
import { FaTimes, FaCopy, FaWhatsapp, FaTelegramPlane, FaFileAlt, FaSpinner } from 'react-icons/fa';
import Toast from './Toast';

export default function ReportModal({ isOpen, onClose, categoryFilter = 'ALL' }) {
    const [reportText, setReportText] = useState('');
    const [loading, setLoading] = useState(false);
    const [toast, setToast] = useState({ show: false, message: '', type: 'success' });

    // --- LOGIC GENERATOR TEKS ---
    const generateText = (data) => {
        // 1. DEFINISI ICON UNICODE (Agar terbaca benar di WA)
        const ICON_CHECK  = '\u2705'; // ✅ (Centang Hijau)
        const ICON_CROSS  = '\u274C'; // ❌ (Silang Merah)
        const ICON_PAUSE  = '\u23F8'; // ⏸️ (Pause/SC)
        
        const running = data.running || [];
        const closed = data.closed || [];
        const total = running.length + closed.length;
        
        const now = new Date();
        const optionsDate = { timeZone: 'Asia/Jakarta', day: '2-digit', month: '2-digit', year: 'numeric' };
        const optionsTime = { timeZone: 'Asia/Jakarta', hour: '2-digit', minute: '2-digit', hour12: false };
        const tanggal = new Intl.DateTimeFormat('id-ID', optionsDate).format(now).replace(/\//g, '-');
        const jam = new Intl.DateTimeFormat('id-ID', optionsTime).format(now).replace(':', '.');

        let t = `*Monitoring Tiket ${categoryFilter === 'ALL' ? 'SEMUA KATEGORI' : categoryFilter} Area Bekasi*\n`;
        t += `*Tanggal : ${tanggal}*\n`;
        t += `*Jam : ${jam}*\n`;
        t += `================================\n`;
        
        t += `*).Jumlah Tiket Total : ${total} Tiket*\n`;
        t += `- Sisa Tiket Running : ${running.length} tiket\n`;
        t += `- Tiket Closed Hari Ini : ${closed.length} tiket\n\n`;

        // --- HELPER FORMAT TEKNISI ---
        const formatTeknisi = (tik) => {
            let pic = tik.technician_name || tik.technician_names || '-';
            // Jika ada partner, gabungkan text-nya
            if (tik.partner_technicians) {
                // Contoh output: "Budi (Support: Asep, Ujang)"
                return `${pic}, ${tik.partner_technicians}`;
            }
            return pic;
        };

        // --- LOOP CLOSED ---
        if (closed.length > 0) {
            t += `*)Closed : ${closed.length} tiket\n`;
            closed.forEach((tik, i) => {
                t += `${i + 1}. ${ICON_CHECK} ${tik.id_tiket}  ${tik.deskripsi || '-'}\n`;
                t += `   RCA : ${tik.update_progres || 'Done'}\n`;
                // Panggil helper formatTeknisi
                t += `   Teknisi : ${formatTeknisi(tik)}\n\n`;
            });
        } else {
            t += `*)Closed : 0 tiket\n\n`;
        }

        // --- LOOP RUNNING ---
        if (running.length > 0) {
            t += `*).ON Progres : ${running.length} tiket\n`;
            running.forEach((tik, i) => {
                const icon = tik.status === 'SC' ? ICON_PAUSE : ICON_CROSS; 
                
                t += `${i + 1}. ${icon} ${tik.id_tiket}  ${tik.deskripsi || '-'}\n`;
                t += `   Update : ${tik.update_progres || 'Belum ada update'}\n`;
                // Panggil helper formatTeknisi
                t += `   Teknisi : ${formatTeknisi(tik)}\n\n`;
            });
        } else {
            t += `*).ON Progres : 0 tiket\n`;
        }

        t += `----------------------------------------\n`;
        t += `_Generated by Dashboard System_`;
        
        return t;
    };

    useEffect(() => {
        if (isOpen) {
            setLoading(true);
            setReportText(''); 
            
            fetch(`/api/reports/daily?category=${categoryFilter}`)
                .then(res => res.json())
                .then(data => {
                    const text = generateText(data);
                    setReportText(text);
                })
                .catch(err => {
                    setReportText('Gagal memuat data laporan: ' + err.message);
                })
                .finally(() => setLoading(false));
        }
    }, [isOpen, categoryFilter]);

    const handleCopy = () => {
        navigator.clipboard.writeText(reportText);
        setToast({ show: true, message: 'Laporan berhasil disalin ke clipboard!', type: 'success' });
    };

    const handleSendWA = () => {
        const url = `https://wa.me/?text=${encodeURIComponent(reportText)}`;
        window.open(url, '_blank');
    };

    const handleSendTelegram = () => {
        const url = `https://t.me/share/url?url=${encodeURIComponent(' ')}&text=${encodeURIComponent(reportText)}`;
        window.open(url, '_blank');
    };

    if (!isOpen) return null;

    return (
        <>
            {toast.show && <Toast message={toast.message} type={toast.type} onClose={() => setToast({ ...toast, show: false })} />}

            <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-sm p-4 animate-fade-in">
                <div className="w-full max-w-5xl bg-white rounded-2xl shadow-2xl overflow-hidden flex flex-col h-[90vh]">
                    
                    {/* --- HEADER --- */}
                    <div className="bg-gradient-to-r from-slate-900 to-slate-800 px-6 py-4 flex justify-between items-center text-white border-b border-slate-700 shrink-0">
                        <h3 className="font-bold text-lg flex items-center gap-3">
                            <div className="bg-white/10 p-2 rounded-lg">
                                <FaFileAlt className="text-blue-400" />
                            </div>
                            Generator Laporan Harian
                        </h3>
                        <button onClick={onClose} className="text-slate-400 hover:text-white hover:bg-white/10 p-2 rounded-full transition-all">
                            <FaTimes size={18} />
                        </button>
                    </div>

                    {/* --- BODY --- */}
                    <div className="p-0 flex-1 overflow-hidden flex flex-col relative bg-slate-50">
                        <div className="bg-blue-50 border-b border-blue-100 px-6 py-3 text-xs text-blue-800 font-medium flex items-center gap-2 shrink-0">
                            <span>ℹ️</span> Silakan review laporan sebelum dikirim. Anda bisa mengedit teks di bawah ini jika diperlukan.
                        </div>

                        <div className="flex-1 relative h-full">
                            {loading ? (
                                <div className="absolute inset-0 flex flex-col items-center justify-center bg-white/50 backdrop-blur-sm z-10">
                                    <FaSpinner className="animate-spin text-4xl text-blue-600 mb-3" />
                                    <p className="text-sm font-semibold text-slate-600">Menyusun data laporan...</p>
                                </div>
                            ) : null}

                            <textarea 
                                className="w-full h-full resize-none border-none p-6 font-mono text-sm text-slate-700 bg-slate-50 focus:ring-0 focus:outline-none leading-relaxed custom-scrollbar"
                                value={reportText}
                                onChange={(e) => setReportText(e.target.value)}
                                spellCheck="false"
                            ></textarea>
                        </div>
                    </div>

                    {/* --- FOOTER --- */}
                    <div className="p-5 bg-white border-t border-slate-200 flex justify-between items-center gap-4 shrink-0">
                        <button 
                            onClick={onClose}
                            className="px-5 py-2.5 rounded-xl text-sm font-bold text-slate-500 hover:bg-slate-100 transition-colors"
                        >
                            Batal
                        </button>
                        
                        <div className="flex gap-3">
                            <button 
                                onClick={handleCopy}
                                disabled={loading || !reportText}
                                className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-slate-100 text-slate-700 font-bold hover:bg-slate-200 border border-slate-200 transition-all active:scale-95 disabled:opacity-50"
                            >
                                <FaCopy /> Salin
                            </button>

                            <button 
                                onClick={handleSendTelegram}
                                disabled={loading || !reportText}
                                className="flex items-center gap-2 px-6 py-2.5 rounded-xl bg-gradient-to-r from-sky-500 to-blue-600 text-white font-bold hover:shadow-lg hover:shadow-sky-500/30 transition-all active:scale-95 disabled:opacity-50"
                            >
                                <FaTelegramPlane className="text-lg" /> Telegram
                            </button>
                            
                            <button 
                                onClick={handleSendWA}
                                disabled={loading || !reportText}
                                className="flex items-center gap-2 px-6 py-2.5 rounded-xl bg-gradient-to-r from-green-500 to-emerald-600 text-white font-bold hover:shadow-lg hover:shadow-green-500/30 transition-all active:scale-95 disabled:opacity-50"
                            >
                                <FaWhatsapp className="text-lg" /> WhatsApp
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}