'use client';

import { useState, useEffect } from 'react';
import { FaTimes, FaCopy, FaWhatsapp, FaTelegramPlane, FaFileAlt, FaSpinner } from 'react-icons/fa';
import Toast from './Toast';

export default function ReportModal({ isOpen, onClose, categoryFilter = 'ALL' }) {
    const [reportText, setReportText] = useState('');
    const [loading, setLoading] = useState(false);
    const [toast, setToast] = useState({ show: false, message: '', type: 'success' });

    // --- LOGIC GENERATOR TEKS ---
    const generateText = (data) => {
        const ICON_CHECK = '\u2705';
        const ICON_CROSS = '\u274C';
        const ICON_PAUSE = '\u23F8';

        const running = data.running || [];
        const closed = data.closed || [];
        const total = running.length + closed.length;

        const now = new Date();
        const optionsDate = { timeZone: 'Asia/Jakarta', day: '2-digit', month: '2-digit', year: 'numeric' };
        const optionsTime = { timeZone: 'Asia/Jakarta', hour: '2-digit', minute: '2-digit', hour12: false };
        const tanggal = new Intl.DateTimeFormat('id-ID', optionsDate).format(now).replace(/\//g, '-');
        const jam = new Intl.DateTimeFormat('id-ID', optionsTime).format(now).replace(':', '.');

        let t = `*Monitoring Tiket ${categoryFilter === 'ALL' ? 'SEMUA KATEGORI' : categoryFilter} Area Bekasi*\n`;
        t += `*Tanggal : ${tanggal}*\n`;
        t += `*Jam : ${jam}*\n`;
        t += `================================\n`;

        t += `*).Jumlah Tiket Total : ${total} Tiket*\n`;
        t += `- Sisa Tiket Running : ${running.length} tiket\n`;
        t += `- Tiket Closed Hari Ini : ${closed.length} tiket\n\n`;

        const formatTeknisi = (tik) => {
            let pic = tik.technician_name || tik.technician_names || '-';
            if (tik.partner_technicians) {
                return `${pic}, ${tik.partner_technicians}`;
            }
            return pic;
        };

        if (closed.length > 0) {
            t += `*)Closed : ${closed.length} tiket\n`;
            closed.forEach((tik, i) => {
                t += `${i + 1}. ${ICON_CHECK} ${tik.id_tiket}  ${tik.deskripsi || '-'}\n`;
                t += `   RCA : ${tik.update_progres || 'Done'}\n`;
                t += `   Teknisi : ${formatTeknisi(tik)}\n\n`;
            });
        } else {
            t += `*)Closed : 0 tiket\n\n`;
        }

        if (running.length > 0) {
            t += `*).ON Progres : ${running.length} tiket\n`;
            running.forEach((tik, i) => {
                const icon = tik.status === 'SC' ? ICON_PAUSE : ICON_CROSS;
                t += `${i + 1}. ${icon} ${tik.id_tiket}  ${tik.deskripsi || '-'}\n`;
                t += `   Update : ${tik.update_progres || 'Belum ada update'}\n`;
                t += `   Teknisi : ${formatTeknisi(tik)}\n\n`;
            });
        } else {
            t += `*).ON Progres : 0 tiket\n`;
        }

        t += `----------------------------------------\n`;
        t += `_Generated by Dashboard System_`;

        return t;
    };

    useEffect(() => {
        if (isOpen) {
            setLoading(true);
            setReportText('');

            fetch(`/api/reports/daily?category=${categoryFilter}`)
                .then(res => res.json())
                .then(data => {
                    const text = generateText(data);
                    setReportText(text);
                })
                .catch(err => {
                    setReportText('Gagal memuat data laporan: ' + err.message);
                })
                .finally(() => setLoading(false));
        }
    }, [isOpen, categoryFilter]);

    const handleCopy = () => {
        navigator.clipboard.writeText(reportText);
        setToast({ show: true, message: 'Laporan berhasil disalin ke clipboard!', type: 'success' });
    };

    const handleSendWA = () => {
        const url = `https://wa.me/?text=${encodeURIComponent(reportText)}`;
        window.open(url, '_blank');
    };

    const handleSendTelegram = () => {
        const url = `https://t.me/share/url?url=${encodeURIComponent(' ')}&text=${encodeURIComponent(reportText)}`;
        window.open(url, '_blank');
    };

    if (!isOpen) return null;

    return (
        <>
            {toast.show && <Toast message={toast.message} type={toast.type} onClose={() => setToast({ ...toast, show: false })} />}

            <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-sm p-4 animate-fade-in">
                <div className="w-full max-w-5xl bg-[var(--bg-surface)] rounded-2xl shadow-2xl overflow-hidden flex flex-col h-[90vh]">

                    {/* --- HEADER --- */}
                    <div className="bg-gradient-to-r from-slate-900 to-slate-800 px-4 py-3 md:px-6 md:py-4 flex justify-between items-center text-white border-b border-slate-700 shrink-0">
                        <h3 className="font-bold text-base md:text-lg flex items-center gap-3">
                            <div className="bg-white/10 p-2 rounded-lg">
                                <FaFileAlt className="text-blue-400" />
                            </div>
                            Generator Laporan
                        </h3>
                        <button onClick={onClose} className="text-slate-400 hover:text-white hover:bg-white/10 p-2 rounded-full transition-all">
                            <FaTimes size={18} />
                        </button>
                    </div>

                    {/* --- BODY --- */}
                    <div className="p-0 flex-1 overflow-hidden flex flex-col relative bg-[var(--bg-base)]">
                        <div className="bg-blue-50 dark:bg-blue-900/20 border-b border-blue-100 dark:border-blue-800 px-4 py-2 md:px-6 md:py-3 text-[10px] md:text-xs text-blue-800 dark:text-blue-300 font-medium flex items-center gap-2 shrink-0">
                            <span>ℹ️</span> Silakan review laporan sebelum dikirim.
                        </div>

                        <div className="flex-1 relative h-full">
                            {loading ? (
                                <div className="absolute inset-0 flex flex-col items-center justify-center bg-[var(--bg-surface)]/50 backdrop-blur-sm z-10">
                                    <FaSpinner className="animate-spin text-4xl text-blue-600 dark:text-blue-400 mb-3" />
                                    <p className="text-sm font-semibold text-[var(--text-secondary)]">Menyusun data laporan...</p>
                                </div>
                            ) : null}

                            <textarea
                                className="w-full h-full resize-none border-none p-4 md:p-6 font-mono text-xs md:text-sm text-[var(--text-primary)] bg-[var(--bg-base)] focus:ring-0 focus:outline-none leading-relaxed custom-scrollbar"
                                value={reportText}
                                onChange={(e) => setReportText(e.target.value)}
                                spellCheck="false"
                            ></textarea>
                        </div>
                    </div>

                    {/* --- FOOTER (MOBILE RESPONSIVE) --- */}
                    <div className="p-4 md:p-5 bg-[var(--bg-surface)] border-t border-[var(--border-color)] flex flex-col md:flex-row justify-between items-center gap-3 shrink-0">

                        {/* TOMBOL BATAL */}
                        <button
                            onClick={onClose}
                            className="w-full md:w-auto px-5 py-2.5 rounded-xl text-sm font-bold text-[var(--text-muted)] hover:bg-[var(--bg-base)] transition-colors order-2 md:order-1"
                        >
                            Batal
                        </button>

                        {/* GROUP TOMBOL AKSI */}
                        <div className="flex flex-col md:flex-row gap-2 md:gap-3 w-full md:w-auto order-1 md:order-2">
                            <button
                                onClick={handleCopy}
                                disabled={loading || !reportText}
                                className="w-full md:w-auto flex justify-center items-center gap-2 px-5 py-2.5 rounded-xl bg-[var(--bg-base)] text-[var(--text-primary)] font-bold hover:opacity-80 border border-[var(--border-color)] transition-all active:scale-95 disabled:opacity-50"
                            >
                                <FaCopy /> Salin
                            </button>

                            <button
                                onClick={handleSendTelegram}
                                disabled={loading || !reportText}
                                className="w-full md:w-auto flex justify-center items-center gap-2 px-6 py-2.5 rounded-xl bg-gradient-to-r from-sky-500 to-blue-600 text-white font-bold hover:shadow-lg hover:shadow-sky-500/30 transition-all active:scale-95 disabled:opacity-50"
                            >
                                <FaTelegramPlane className="text-lg" /> Telegram
                            </button>

                            <button
                                onClick={handleSendWA}
                                disabled={loading || !reportText}
                                className="w-full md:w-auto flex justify-center items-center gap-2 px-6 py-2.5 rounded-xl bg-gradient-to-r from-green-500 to-emerald-600 text-white font-bold hover:shadow-lg hover:shadow-green-500/30 transition-all active:scale-95 disabled:opacity-50"
                            >
                                <FaWhatsapp className="text-lg" /> WhatsApp
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}